-- Secuencias
CREATE SEQUENCE seq_lenguajes_programacion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_programadores START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyectos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_programador_lenguaje START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyecto_programador START WITH 1 INCREMENT BY 1;